include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/**

linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: false
    avoid_relative_lib_imports: true
    unawaited_futures: true
    always_use_package_imports: true